name: updpkgsums
on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  updpkgsums:
    runs-on: ubuntu-22.04
    steps:
      -
        uses: actions/checkout@v4
        with:
          path: qbootctl
          fetch-depth: '1'
      -
        name: install-build-dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt install \
            meson \
            libarchive-dev 
            #asciidoc
      -
        name: install pacman
        shell: bash
        env:
          PACMAN_VERSION: 6.0.2
        run: |
          sudo git clone --depth 1 https://gitlab.manjaro.org/packages/core/pacman.git
          pushd pacman
            sudo wget https://sources.archlinux.org/other/pacman/pacman-${PACMAN_VERSION}.tar.xz
            sudo tar -xvf pacman-${PACMAN_VERSION}.tar.xz
            pushd pacman-${PACMAN_VERSION}
            #  sudo patch -p1 -i ../pacman-sync-first-option.patch Removed
              sudo meson --prefix=/usr \
                        --buildtype=plain \
                        -Ddoc=disabled \
                        -Ddoxygen=enabled \
                        -Dscriptlet-shell=/usr/bin/bash \
                        -Dldconfig=/usr/bin/ldconfig \
                        build
              sudo meson compile -C build
              sudo meson install -C build
            popd
            sudo install -m644 pacman.conf /etc/pacman.conf
            sudo install -m644 makepkg.conf /etc/
            sudo mkdir -p /etc/pacman.d
            sudo touch /etc/pacman.d/mirrorlist
          popd
      -
        name: install pacman-contrib
        shell: bash
        run: |
          git clone --depth=1 https://gitlab.archlinux.org/pacman/pacman-contrib.git pacman-contrib
          cd pacman-contrib
          ./autogen.sh
          ./configure --prefix=/usr \
            --sysconfdir=/etc \
            --localstatedir=/var \
            --disable-doc
          make
          make check
          sudo make install

